
name: Testing data
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: 
    - cron: '0 * * * *'
jobs:
  testing-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Creating and activating virtualenv
        run: |
          pip3 install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Installing dependencies
        run: |
          pip install -r requirements.txt
      - name: Testing training
        run: |
          cd app/
          python3 test_api.py